GET http://localhost:3001/

###
GET http://localhost:3001/info/

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/62e146b13f1c54cmfdkkmsldma782d1ff3c

###
GET http://localhost:3001/api/persons/62e146b13f1c54c782d1ff3c

###
GET http://localhost:3001/api/persons/30